default_chain: stride-testnet
chains:
  gaia-testnet:
    key: test
    chain-id: GAIA
    rpc-addr: http://gaia1:26657
    grpc-addr: http://gaia1:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: test
    chain-id: STRIDE
    rpc-addr: http://stride1:26657
    grpc-addr: http://stride1:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
